### ISSUE TITLE
Merikarttasarja F

### ISSUE THREAD

**Issue by juffe84** [horsmik/merikartat#1]
Miten pystyisi tekemään muita sarjoja? Mitä muutosta tarvii koodiin?

Mistä sait haettua oikeat tileranget karttalehtiin?

**Comment by horsmik** [comment]
moro! Kulmien löytäminen oli aika työlästä ja tein sen pitkälti manuaalisesti. Minulla oli varsinaiset karttasarjat paperilla ja niistä katsomalla ja kokeilemalla löytyi suunnilleen oikea karttatiili. Suurella resoluutiolla yhteen karttatiileen ei mahdu kuin postimerkin kokoinen pala kartasta, joten tuo on lievästi työlästä. Tein lopulta pienen apuohjelman, mille voi syöttää karttalehdestä mitatut koordinaatit vastakkaisille kulmille ja apuohjelma sitten laski ja ehdotti mitkä tiilien numerot voisivat olla. Sinänsä karttalehtien koko ja muoto voisi olla minkälainen hyvänsä, ei niiden välttämättä tarvitsisi noudattaa paperisen karttakirjan sivujakoa. Tuolla tavalla tehtynä homma olisi paljon helpompi.

**Comment by horsmik** [comment]
Lisäsin em. apuohjelman. Karttalehden koordinaatit joutuu syöttämään suoraan scriptiin.
