### ISSUE TITLE
liikennevirasto --> Traficom

### ISSUE THREAD

**Issue by pekkaleh** [horsmik/merikartat#3]
Terve! En keksinyt muuta tapaa ottaa yhteyttä niin avaan siis issuen. Ensin iso kiitos koodista! Omat kyvyt eivät riittäneet käyttämään saati ymmärtämään tuota valtion WMTS systeemiä. Nyt tajuan jo jotain. :)

Sellaisen havainnon tein että tuolla APIssa liikennevirasto on muuttunut Traficomiksi. Kun CSV-tiedostot päivitteli niin scriptit toimivat taas oikein.

Pekka

**Comment by horsmik** [comment]
Moi! Juu, kiitoksia, tämä oli hauska projekti. Pahoittelun viivästyneestä vastauksesta, en juurikaan ylläpidä tätä ohjelmaa.

Alussa olin itsekin täysin pihalla, miten tuota rajapintaa käytetään, eikä mistään tuntunut löytyvät selkokielisiä ohjeita  API:n sielunelämään. Lopputuloksesta tuli kuitenkin jokseenkin toimiva.

Rajapinta näyttää tosiaan päivittyneen. Nähtävästi täytyy päivittää csv aineistoihin kartta-aineiston nimeen Traficom ja API:n url osoitekin on vaihtunut. Validi kutsu näyttää nyt tältä:

[https://julkinen.traficom.fi/rasteripalvelu/wmts?request=GetTile&version=1.0.0&service=wmts&layer=Traficom:Merikarttasarja C public&TILEMATRIXSET=WGS84_Pseudo-Mercator&TileMatrix=WGS84_Pseudo-Mercator:15&tilerow=9524&tilecol=18334&format=image/png&style=default](https://julkinen.traficom.fi/rasteripalvelu/wmts?request=GetTile&version=1.0.0&service=wmts&layer=Traficom:Merikarttasarja%20C%20public&TILEMATRIXSET=WGS84_Pseudo-Mercator&TileMatrix=WGS84_Pseudo-Mercator:15&tilerow=9524&tilecol=18334&format=image/png&style=default)

Teen ohjelmasta jossain vaiheessa uuden version.

**Comment by horsmik** [comment]
Korjattu
